hacker_news/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users

  resources :posts do
    resources :comments
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#delete'

end

hacker_news/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

  validates :body, presence: true
  validates :post_id, presence: true
  validates :user_id, presence: true

end

hacker_news/app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments#, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

end

hacker_news/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :posts
  has_many :comments

  validates :username, presence: true, uniqueness:true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true

end

hacker_news/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
# If you use a before_action you have access to the @current_user variable everywhere
  # before_action :current_user
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    else
      return nil
    end
  end
  # Re-write it like this for clarity/cleanness
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end

  def require_logged_in
    # indentation
  redirect_to root_path unless is_authenticated?
  end

  def is_authenticated?
    return !!session[:user_id]
  end

end

hacker_news/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # if there were more actions here, you could do a before_action only on new and create
  # something like before_action require_logged_in, only: [:new, :create]
  def new
    require_logged_in
    @comment = Comment.new
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: session[:user_id])
  end

  def create
    require_logged_in
    user = User.find_by(id: session[:user_id])
    post = Post.find_by(id: params[:post_id])
    comment = Comment.new(comment_params)
    comment.user = user
    comment.post = post
    comment.save!
    # error handling
    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

hacker_news/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    require_logged_in
    @user = User.find_by(id: session[:user_id])
    @post = Post.new
  end

  def create
    require_logged_in
    user = User.find_by(id: session[:user_id])
    post = Post.new(post_params)
    post.user = user
    post.save!
    redirect_to posts_path
  end

  def index
    if current_user
    @user = User.find_by(id: session[:user_id])
    @posts = Post.where(user_id: session[:user_id])
    else
    redirect_to login_path
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    # Use your associations
    # @user = @post.user
    @user = User.find_by(id: @post.user_id)
    # @comments = @post.comments
    @comments = Comment.where(post_id: @post.id)
  end

  def edit
    require_logged_in
    @post = Post.find_by(id: params[:id])
  end

  def update
    require_logged_in
    post = Post.find_by(id: params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end

  def destroy
    require_logged_in
    # This line is unnecessary right now but could be useful if you are comparing @user.id to @post.id to make sure only the post's author can destroy it.
    # @user = User.find_by(id: current_user.id)
    post = Post.find_by(id: params[:id]).destroy
    # see note in Post model to also delete associated comments
    # You would need to break that up into two pieces for error handling - find post first, then "if post.destroy (do stuff) else (error handling)"
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

end

hacker_news/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def delete
    session[:user_id] = nil
    # session.delete(:user_id) <-- removing the key and not just setting it nil
    redirect_to root_path
  end

end

hacker_news/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_post_path
    end
  end

  def edit
    require_logged_in
    @user = User.find_by(id: session[:user_id])
  end

  def update
    require_logged_in
    user = User.find_by(session[:user_id])
    user.update(user_params)
    redirect_to root_path
  end

  def show
    require_logged_in
    @user = User.find_by(id: session[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password)
  end

end

hacker_news/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      @user = User.find_by(id: current_user.id)
      @posts = Post.all.reverse
      # Imagine your db had a million posts? Try using limit and order.
    else
      @posts = Post.all.reverse
    end
  end

end

hacker_news/app/helpers/application_helper.rb
module ApplicationHelper

  def my_date(time_object)
    time_object.strftime("Created at: %m/%d/%Y")
  end

  def elapsed_time(datetime)
    current_time = Time.now
    distance_of_time_in_words(current_time, datetime)
  end

end

hacker_news/app/helpers/comments_helper.rb
module CommentsHelper
  # remove empty files
end

hacker_news/app/helpers/posts_helper.rb
module PostsHelper
end

hacker_news/app/helpers/sessions_helper.rb
module SessionsHelper
end

hacker_news/app/helpers/users_helper.rb
module UsersHelper
end

hacker_news/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hacker_news/app/views/comments/new.html.erb
<h2>Add a comment!</h2>

<div class='form'>
  <%= form_for([@post, @comment], url: :post_comments) do |f| %>
    <div>
      <%= f.label :body %>
      <%= f.text_area :body, :rows => 20, :cols =>70 %>
    </div>
    <div>
      <%= f.submit 'submit' %>
    </div>
  <% end %>
</div>

hacker_news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Hacker News Clone</h1>
    <div id='nav_bar'>
      <%= button_to 'Home', root_path, method: :get, class: 'btn' %>
        <% if session[:user_id] %>
          <%= button_to 'Profile', user_path(@user), method: :get, class: 'btn' %>
          <%= button_to 'View your posts', posts_path, method: :get, class: 'btn' %>
          <%= button_to 'Create a new post', new_post_path(@user), method: :get %>
          <%= button_to 'Log Out', logout_path, method: :delete, class: 'btn' %>
        <% else %>
          <%= button_to 'Log In', login_path, method: :get, class: 'btn' %>
          <%= button_to 'Sign Up', new_user_path, method: :get, class: 'btn' %>
        <% end %>
    </div>
  </header>

<%= yield %>

</body>
</html>

hacker_news/app/views/posts/_post.html.erb
    <div class='post'>
    <div><%= link_to post.title, post_path(post) %></div>
    <div>(Author: <%= post.user.username %>)</div>
    <div><%= my_date(post.created_at) %></div>
    <div>upvotes: <span id="<%='span' + post.id.to_s %>"><%= post.vote_count %></span></div>
    <%= button_to 'upvote', upvote_path(post), form_class: 'upvote_form', method: :put %>
    <div class='comment_field'>
      <div>Comments: <%= post.comments.count %></div>
    </div>
    </div>

hacker_news/app/views/posts/edit.html.erb
<h2>Edit your post here!</h2>

<div class='form'>
  <%= form_for @post do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :body %>
      <%= f.text_area :body, :rows => 20, :cols =>70 %>
    </div>
    <div>
      <%= f.submit "Edit" %>
    </div>
  <% end %>
</div>

hacker_news/app/views/posts/index.html.erb
<h2>Here are all your posts, <%= @user.username %> !</h2>

<div class='posts'>
  <% @posts.each do |post| %>
    <%= render post %>
    <%= button_to 'Edit this post', edit_post_path(post), method: :get, class: 'btn' %>
    <br>
    <%= button_to 'Delete this post', post_path(post), method: :delete, class: 'btn' %>
    <br>
  <% end %>

</div>

hacker_news/app/views/posts/new.html.erb
<h2>Create your post here!</h2>

<div class='form'>
  <%= form_for @post do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :body %>
      <%= f.text_area :body, :rows => 20, :cols =>70 %>
    </div>
    <div>
      <%= f.submit "Post", class: 'btn' %>
    </div>
  <% end %>
</div>

hacker_news/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<div><%= @post.body %></div>

<div>Author: <%= @user.username %></div>

<div><%= my_date(@post.created_at) %></div>

<% if session[:user_id] == @post.user_id %>
  <br>
  <%= button_to 'Edit this post', edit_post_path(@post), method: :get, class: 'btn' %>
  <br>
  <%= button_to 'Delete this post', post_path(@post), method: :delete, class: 'btn' %>
  <br>
<% end %>

<br>
<%= button_to 'comment', new_post_comment_path(@post), method: :get, class: 'btn' %>
<br>
<h3>Comments</h3>
<div class='comments'>
  <% @comments.each do |comment| %>
    <div class ='comment-body'><%= comment.body %></div>
    <div>posted: <%= elapsed_time(comment.created_at) %></div>
    <br>
  <% end %>
</div>

hacker_news/app/views/users/edit.html.erb
<h2>Edit your profile here!</h2>
<div>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <br>
    <div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>
</div>

hacker_news/app/views/users/new.html.erb
<h2>Sign up here!</h2>
<div>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit "Sign Up!" %>
    </div>
  <% end %>
</div>

hacker_news/app/views/users/show.html.erb
<h2>Hello <%= @user.username %></h2>
<h3>Here is your profile</h3>

<div class='user_profile'>
  <div>Username: <%= @user.username %></div>
  <div>First Name: <%= @user.first_name %></div>
  <div>Last Name: <%= @user.last_name %></div>
</div>
<br>
<%= button_to 'edit', edit_user_path(@user), method: :get, class: 'btn' %>

hacker_news/app/views/welcome/index.html.erb
<h2>Here are the current posts</h2>
<div>
  <% if session[:user_id] %>
    <% @posts.each do |post| %>
      <%= render post %>
    <br>
    <br>
    <% end %>
</div>
<br>
  <% else %>
    <% @posts.each do |post| %>
    <%= render post %>
    <br>
    <br>
    <% end %>
  <% end %>